/*

 LEVELMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 18
   Tile set      : leveltiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define levelmapWidth 18
#define levelmapHeight 18
#define levelmapBank 0

extern unsigned char levelmap[];

/* End of LEVELMAP.H */
